// ==================== 台词飞花 / 经典复刻 / 看图猜影视 数据库 ====================
// 台词飞花: 280+ 经典台词 | 经典复刻: 140+ 场景描述 | 看图猜影视: 130+ 表情谜题

// ==================== 台词飞花 - 经典台词库 ====================
const quoteBattleData = {
  movie: [
    { quote: '曾经有一份真诚的爱情放在我面前，我没有珍惜，等我失去的时候我才后悔莫及', answer: '如果上天能够给我一个再来一次的机会，我会对那个女孩子说三个字：我爱你', source: '大话西游' },
    { quote: '人生就像一盒巧克力', answer: '你永远不知道下一颗是什么味道', source: '阿甘正传' },
    { quote: '做人如果没有梦想', answer: '那跟咸鱼有什么区别', source: '少林足球' },
    { quote: '我养你啊', answer: '你先照顾好你自己吧', source: '喜剧之王' },
    { quote: '说的是一辈子', answer: '差一年，一个月，一天，一个时辰，都不算一辈子', source: '霸王别姬' },
    { quote: '希望是美好的', answer: '也许是人间至善，而美好的事物永不消逝', source: '肖申克的救赎' },
    { quote: '你跳，我也跳', answer: 'Jack，我飞起来了', source: '泰坦尼克号' },
    { quote: '能力越大', answer: '责任越大', source: '蜘蛛侠' },
    { quote: '我不是针对你', answer: '我是说在座的各位都是垃圾', source: '英雄本色' },
    { quote: '我等了三年', answer: '就是要等一个机会，我要争一口气', source: '英雄本色' },
    { quote: '出来混', answer: '迟早要还的', source: '无间道' },
    { quote: '对不起，我是警察', answer: '谁知道', source: '无间道' },
    { quote: '我要站着把钱挣了', answer: '寒碜，很寒碜', source: '让子弹飞' },
    { quote: '我要这天', answer: '再遮不住我眼', source: '悟空传' },
    { quote: '不要温和地走进那个良夜', answer: '老年应当在日暮时燃烧咆哮', source: '星际穿越' },
    { quote: '我们一路奋战', answer: '不是为了改变世界，而是为了不让世界改变我们', source: '熔炉' },
    { quote: '有些鸟是关不住的', answer: '它们的羽毛太丰润了', source: '肖申克的救赎' },
    { quote: '愿原力与你同在', answer: 'May the Force be with you', source: '星球大战' },
    { quote: '我会回来的', answer: "I'll be back", source: '终结者' },
    { quote: '我是钢铁侠', answer: 'I am Iron Man', source: '复仇者联盟4' },
    { quote: '爱你三千遍', answer: 'I love you 3000', source: '复仇者联盟4' },
    { quote: '包租婆', answer: '怎么没水了呢', source: '功夫' },
    { quote: '一支穿云箭', answer: '千军万马来相见', source: '功夫' },
    { quote: '别人笑我太疯癫', answer: '我笑他人看不穿', source: '唐伯虎点秋香' },
    { quote: '小强，你怎么了小强', answer: '小强你不能死啊', source: '唐伯虎点秋香' },
    { quote: '不上班行不行啊', answer: '不上班你养我啊', source: '喜剧之王' },
    { quote: '你看那个人', answer: '好奇怪哟，他好像一条狗啊', source: '大话西游' },
    { quote: '我的意中人是个盖世英雄', answer: '有一天他会踩着七色云彩来娶我', source: '大话西游' },
    { quote: '我猜中了前头', answer: '可是我猜不着这结局', source: '大话西游' },
    { quote: '如果不能再拥有', answer: '唯一能做的就是不要忘记', source: '东邪西毒' },
    { quote: '你连死都不怕', answer: '还怕活着吗', source: '活着' },
    { quote: '不如我们从头来过', answer: '黎耀辉，让我们从头来过', source: '春光乍泄' },
    { quote: '有些事情不用一个晚上做完', answer: '我们又不赶时间', source: '志明与春娇' },
    { quote: '往前走', answer: '别回头', source: '山河故人' },
    { quote: '你保护世界', answer: '我保护你', source: '少年的你' },
    { quote: '道路千万条', answer: '安全第一条', source: '流浪地球' },
    { quote: '我命由我不由天', answer: '是魔是仙，我自己说了算', source: '哪吒之魔童降世' },
    { quote: '若命运不公', answer: '就和它斗到底', source: '哪吒之魔童降世' },
    { quote: '人心中的成见是一座大山', answer: '任你怎么努力都休想搬动', source: '哪吒之魔童降世' },
    { quote: '犯我中华者', answer: '虽远必诛', source: '战狼' },
    { quote: '当你在凝视深渊的时候', answer: '深渊也正在凝视着你', source: '唐人街探案' },
    { quote: '请记住我', answer: '虽然我要去远方', source: '寻梦环游记' },
    { quote: '你的心是自由的', answer: '要有勇气去追寻它', source: '勇敢的心' },
    { quote: '他们也许能夺走我们的生命', answer: '但永远夺不走我们的自由', source: '勇敢的心' },
    { quote: '我就是想站着', answer: '还把钱挣了', source: '让子弹飞' },
    { quote: '你给我翻译翻译', answer: '什么叫惊喜', source: '让子弹飞' },
    { quote: '天下风云出我辈', answer: '一入江湖岁月催', source: '东方不败' },
    { quote: '有人就有恩怨', answer: '有恩怨就有江湖，人就是江湖', source: '笑傲江湖' },
    { quote: '世间所有的相遇', answer: '都是久别重逢', source: '一代宗师' },
    { quote: '念念不忘', answer: '必有回响', source: '一代宗师' },
    { quote: '见自己', answer: '见天地，见众生', source: '一代宗师' },
    { quote: '别让任何人告诉你', answer: '你不能做什么', source: '当幸福来敲门' },
    { quote: '如果你有梦想', answer: '就要去捍卫它', source: '当幸福来敲门' },
    { quote: '死亡不是终点', answer: '遗忘才是', source: '寻梦环游记' },
    { quote: '生亦何欢', answer: '死亦何苦', source: '大话西游' },
    { quote: '不疯魔不成活', answer: '从一而终', source: '霸王别姬' },
    { quote: '正经人谁写日记啊', answer: '是啊', source: '邪不压正' },
    { quote: '醉里挑灯看剑', answer: '梦回吹角连营', source: '东邪西毒' },
    { quote: '全世界的不相信，我只要相信你', answer: '就够了', source: '志明与春娇' },
    { quote: '我们为什么不能都做好人呢', answer: '因为这个世界不允许', source: '少年的你' },
    { quote: '烧鸡翼', answer: '我中意食', source: '唐伯虎点秋香' },
    { quote: '假如再也见不到你', answer: '祝你早安午安晚安', source: '楚门的世界' },
    { quote: '明天又是新的一天', answer: 'After all tomorrow is another day', source: '乱世佳人' },
    { quote: '世界上只有一种病', answer: '那就是穷病', source: '我不是药神' },
    { quote: '我不是想赢', answer: '我只是不想输', source: '飞驰人生' },
    { quote: '马冬什么', answer: '马冬梅', source: '夏洛特烦恼' },
    { quote: '什么冬梅', answer: '马冬梅啊', source: '夏洛特烦恼' },
    { quote: '马什么梅', answer: '马冬梅', source: '夏洛特烦恼' },
    { quote: '明明说三年', answer: '三年之后又三年', source: '无间道' },
    { quote: '三年之后又三年', answer: '都快十年了老大', source: '无间道' },
    { quote: '高音甜中音准低音沉', answer: '总之一句话就是通透', source: '无间道' },
    { quote: '一切安好', answer: 'All is well', source: '三傻大闹宝莱坞' },
    { quote: '为你', answer: '千千万万遍', source: '追风筝的人' },
    { quote: 'I see you', answer: '我看见你', source: '阿凡达' },
    { quote: '永远不要恨你的敌人', answer: '那会影响你的判断力', source: '教父' },
    { quote: '有些人只想看这个世界燃烧', answer: '因为他能', source: '黑暗骑士' },
    { quote: '你为什么这么严肃', answer: '怎么不笑一个', source: '黑暗骑士' },
    { quote: '做梦就要做大点', answer: '既然是做梦就做大一点', source: '盗梦空间' },
    { quote: '每个人都会死', answer: '但不是每个人都真正活过', source: '勇敢的心' },
    { quote: '不管你在世界哪个地方', answer: '我一定会去见你', source: '你的名字' },
    { quote: '你快回火星去吧', answer: '地球很危险的', source: '少林足球' },
    { quote: '不知道从什么时候开始', answer: '每个东西上面都有个日期', source: '重庆森林' },
    { quote: '连保鲜纸都会过期', answer: '我开始怀疑还有什么不会过期', source: '重庆森林' },
    { quote: '我们最接近的时候', answer: '我跟她之间的距离只有0.01公分', source: '重庆森林' },
    { quote: '我读书少你不要骗我', answer: '是不是这个意思', source: '鹿鼎记' },
    { quote: '谁赞成谁反对', answer: '我反对', source: '黑金' },
    { quote: '喜欢一个人需要理由吗', answer: '不需要吗', source: '大话西游' },
    { quote: '每天你都有机会和很多人擦身而过', answer: '有些人可能会变成你的朋友或者知己', source: '重庆森林' },
    { quote: '真正的死亡', answer: '是世界上再没有一个人记得你', source: '寻梦环游记' },
    { quote: '三十功名尘与土', answer: '八千里路云和月', source: '满江红' },
    { quote: '我最讨厌你们这些打劫的了', answer: '一点技术含量都没有', source: '天下无贼' },
    { quote: '这世界上有一种鸟是没有脚的', answer: '它只能一直飞呀飞', source: '阿飞正传' },
    { quote: '不要忘记你的名字', answer: '不然就找不到回家的路', source: '千与千寻' },
    { quote: '曾经发生的事不可能忘记', answer: '只是想不起来而已', source: '千与千寻' },
    { quote: '选择生活', answer: '选择一个未来', source: '猜火车' },
    { quote: '有些人见三百次也没用', answer: '有些人见三次就够了', source: '重庆森林' },
    { quote: '我相信善良的人', answer: '运气不会太差', source: '飞驰人生' },
    { quote: '我只想要一个平凡的生活', answer: '可是命运不允许', source: '少年的你' },
    { quote: '大锤八十', answer: '小锤四十', source: '装修' },
    { quote: '人要是没有梦想', answer: '和咸鱼有什么分别', source: '少林足球' },
    { quote: '我命由我', answer: '不由天', source: '哪吒之魔童降世' },
    { quote: '哥只是个传说', answer: '不要迷恋哥', source: '疯狂的石头' },
    { quote: '你看着我', answer: '看着我干什么', source: '无名之辈' },
    { quote: '这个世界会好吗', answer: '会的', source: '我不是药神' },
    { quote: '我把一切都给你', answer: '你把快乐还给我', source: '夏洛特烦恼' },
    { quote: '有些路走下去会很累', answer: '但不走会后悔', source: '无名之辈' },
    { quote: '我只想做个普通人', answer: '过普通的生活', source: '无名之辈' },
    { quote: '你想当英雄吗', answer: '我想当个好人', source: '无间道' },
    { quote: '如果你不出去走走', answer: '你会以为这就是世界', source: '楚门的世界' },
    { quote: '每一次说再见', answer: '都是为了更好的重逢', source: '寻梦环游记' },
    { quote: '一切都是最好的安排', answer: '这就是命运的模样', source: '流浪地球' },
    { quote: '我不想当什么英雄', answer: '我只想回家', source: '流浪地球' },
    { quote: '一万年太久', answer: '只争朝夕', source: '大话西游' },
    { quote: '我们都活在阴沟里', answer: '但仍有人仰望星空', source: '少年的你' },
    { quote: '我就是我', answer: '是颜色不一样的烟火', source: '霸王别姬' },
    { quote: '一念成佛', answer: '一念成魔', source: '唐人街探案' },
    { quote: '做你自己', answer: '因为别人都有人做了', source: '小丑' },
    { quote: '在成为英雄之前', answer: '先做好一个普通人', source: '蜘蛛侠' },
    { quote: '我不是英雄', answer: '我只是做了该做的事', source: '钢铁侠' },
    { quote: '当你凝视星空', answer: '星空也在凝视着你', source: '流浪地球' },
    { quote: '这个世界不值得', answer: '但你值得', source: '小丑' },
    { quote: '我们终将上岸', answer: '阳光万里', source: '飞驰人生' },
  ],
  skit: [
    { quote: '改革春风吹满地', answer: '中国人民真争气', source: '昨天今天明天' },
    { quote: '眼睛一闭一睁', answer: '一天过去了，嚎', source: '不差钱' },
    { quote: '眼睛一闭不睁', answer: '这辈子就过去了，嚎', source: '不差钱' },
    { quote: '人生最痛苦的事', answer: '人死了钱没花了', source: '不差钱' },
    { quote: '人生最最痛苦的事', answer: '人活着钱没了', source: '不差钱' },
    { quote: '这个可以有', answer: '这个真没有', source: '不差钱' },
    { quote: '你太有才了', answer: '那是必须的', source: '不差钱' },
    { quote: '感谢你八辈祖宗', answer: '我做鬼也不会放过你们', source: '不差钱' },
    { quote: '人生最大的痛苦', answer: '人死了钱没花了', source: '不差钱' },
    { quote: '我说人这一辈子', answer: '跟睡觉是一样一样的', source: '不差钱' },
    { quote: '我叫白云', answer: '我叫黑土', source: '昨天今天明天' },
    { quote: '我七十一', answer: '我七十五', source: '昨天今天明天' },
    { quote: '我属鸡', answer: '我属虎', source: '昨天今天明天' },
    { quote: '这是我老公', answer: '这是我老母', source: '昨天今天明天' },
    { quote: '锣鼓喧天', answer: '鞭炮齐鸣', source: '昨天今天明天' },
    { quote: '红旗招展', answer: '人山人海', source: '昨天今天明天' },
    { quote: '相当壮观', answer: '那简直是太壮观了', source: '昨天今天明天' },
    { quote: '九八九八不得了', answer: '粮食大丰收洪水被赶跑', source: '昨天今天明天' },
    { quote: '百姓安居乐业', answer: '齐夸党的领导', source: '昨天今天明天' },
    { quote: '尤其军人', answer: '更是呱呱叫', source: '昨天今天明天' },
    { quote: '给大家拜年了', answer: '祝大家新年快乐', source: '拜年' },
    { quote: '没事儿走两步', answer: '走两步试试', source: '卖拐' },
    { quote: '忽悠', answer: '接着忽悠', source: '卖拐' },
    { quote: '你跺你也麻', answer: '哎还真麻了', source: '卖拐' },
    { quote: '要什么自行车', answer: '要啥自行车啊', source: '卖拐' },
    { quote: '拐了一年又一年', answer: '谢谢噢', source: '卖拐' },
    { quote: '缘分啊', answer: '谢谢噢', source: '卖拐' },
    { quote: '走自己的路', answer: '让别人打车去吧', source: '钟点工' },
    { quote: '穿上马甲我就不认识你了', answer: '穿上马甲我也认识你', source: '钟点工' },
    { quote: '小样儿', answer: '你穿上马甲我就不认识你了', source: '钟点工' },
    { quote: '你怎么是一个人回来', answer: '半个人回来吓死你', source: '相亲' },
    { quote: '我前半生太苦了', answer: '后半生要好好享受', source: '相亲' },
    { quote: '有钱男子汉', answer: '没钱汉子难', source: '相亲' },
    { quote: '你长得跟闹着玩似的', answer: '你长得更闹着玩', source: '相亲' },
    { quote: '同样是一起吃饭', answer: '凭什么你吃肉我喝汤', source: '同桌的你' },
    { quote: '我叫王大拿', answer: '木有啦', source: '捐助' },
    { quote: '一般人我不告诉他', answer: '一般人他也不信啊', source: '打工奇遇' },
    { quote: '宫廷玉液酒', answer: '一百八一杯', source: '打工奇遇' },
    { quote: '这酒怎么样', answer: '听我给你吹', source: '打工奇遇' },
    { quote: '其实就是那个二锅头', answer: '兑的那个白开水', source: '打工奇遇' },
    { quote: '群英荟萃', answer: '萝卜开会', source: '打工奇遇' },
    { quote: '太后', answer: '大饼子', source: '打工奇遇' },
    { quote: '什么叫诚信', answer: '说好不去就不去', source: '打工奇遇' },
    { quote: '人倒了咱不扶', answer: '那人心不就倒了吗', source: '扶不扶' },
    { quote: '人心倒了', answer: '咱想扶也扶不起来', source: '扶不扶' },
    { quote: '我吃不吃', answer: '你得吃啊', source: '吃面条' },
    { quote: '不行重来', answer: '那还重来', source: '吃面条' },
    { quote: '我演的是主角', answer: '你演的是配角', source: '主角与配角' },
    { quote: '主角就得站着', answer: '配角就得趴着', source: '主角与配角' },
    { quote: '你是警察我是小偷', answer: '你抓我跑天经地义', source: '警察与小偷' },
    { quote: '我的大刀早已饥渴难耐了', answer: '那你砍啊', source: '卖车' },
    { quote: '不是我不明白', answer: '这世界变化快', source: '红高粱模特队' },
    { quote: '大锤抡起来', answer: '小锤敲起来', source: '装修' },
    { quote: '八十', answer: '四十', source: '装修' },
    { quote: '你看我还有机会吗', answer: '你看我像不像机会', source: '一句话的事儿' },
    { quote: '你再说一遍', answer: '我就不说了', source: '一句话的事儿' },
    { quote: '我这人不太会说话', answer: '但我会用行动证明', source: '一句话的事儿' },
    { quote: '一个人如果连梦想都没有', answer: '那和咸鱼有什么区别', source: '一句话的事儿' },
    { quote: '我就是这个脾气', answer: '你改不了', source: '一句话的事儿' },
    { quote: '你觉得你行吗', answer: '我行不行你说了不算', source: '投其所好' },
    { quote: '领导喜欢什么', answer: '我就学什么', source: '投其所好' },
    { quote: '这叫什么', answer: '这叫投其所好', source: '投其所好' },
    { quote: '生活不止眼前的苟且', answer: '还有诗和远方', source: '一句话的事儿' },
    { quote: '你幸福吗', answer: '我姓曾', source: '你幸福吗' },
    { quote: '为什么呢', answer: '没有为什么', source: '策划' },
    { quote: '这个事儿吧', answer: '说大不大说小不小', source: '策划' },
    { quote: '我不差钱', answer: '差的是面子', source: '不差钱' },
    { quote: '兄弟你先上', answer: '你先上我不上', source: '策划' },
    { quote: '你这人怎么这样', answer: '我哪样了', source: '一句话的事儿' },
  ],
  tv: [
    { quote: '臣妾做不到啊', answer: '皇上恕罪', source: '甄嬛传' },
    { quote: '贱人就是矫情', answer: '姐姐息怒', source: '甄嬛传' },
    { quote: '皇上', answer: '臣妾要告发熹贵妃私通', source: '甄嬛传' },
    { quote: '这福气给你要不要', answer: '臣妾可担待不起', source: '甄嬛传' },
    { quote: '翠果', answer: '打烂她的嘴', source: '甄嬛传' },
    { quote: '粉色娇嫩', answer: '你如今几岁了', source: '甄嬛传' },
    { quote: '宝鹃', answer: '我的嗓子', source: '甄嬛传' },
    { quote: '不是臣妾的', answer: '是臣妾的错', source: '甄嬛传' },
    { quote: '皇上驾崩了', answer: '四郎你终于走了', source: '甄嬛传' },
    { quote: '嬛嬛一袅楚宫腰', answer: '正是臣女之名', source: '甄嬛传' },
    { quote: '你不要过来', answer: '你不要过来啊', source: '情深深雨蒙蒙' },
    { quote: '你失去的不过是一条腿', answer: '可紫菱失去的是爱情啊', source: '又见一帘幽梦' },
    { quote: '我不是来破坏这个家的', answer: '我是来加入这个家的', source: '情深深雨蒙蒙' },
    { quote: '一分钱一分货', answer: '你出什么价', source: '还珠格格' },
    { quote: '山无棱天地合', answer: '才敢与君绝', source: '还珠格格' },
    { quote: '你是风儿我是沙', answer: '缠缠绵绵到天涯', source: '还珠格格' },
    { quote: '皇上您还记得大明湖畔的夏雨荷吗', answer: '朕当然记得', source: '还珠格格' },
    { quote: '小燕子', answer: '你终于醒了', source: '还珠格格' },
    { quote: '我从未见过如此厚颜无耻之人', answer: '你敢骂我', source: '三国演义' },
    { quote: '俺也一样', answer: '俺也一样俺也一样', source: '三国演义' },
    { quote: '宁可我负天下人', answer: '不可天下人负我', source: '三国演义' },
    { quote: '既生瑜何生亮', answer: '天既生瑜何生亮', source: '三国演义' },
    { quote: '吾观颜良如插标卖首耳', answer: '丞相何出此言', source: '三国演义' },
    { quote: '夜华', answer: '你到底爱不爱我', source: '三生三世十里桃花' },
    { quote: '我不要三生三世', answer: '我只要这一世', source: '三生三世十里桃花' },
    { quote: '一旦遇见便是一眼万年', answer: '一旦开始便是一生', source: '三生三世十里桃花' },
    { quote: '浅浅过来', answer: '过来做什么', source: '三生三世十里桃花' },
    { quote: '韩商言', answer: '一辈子 sumin nai nai', source: '亲爱的热爱的' },
    { quote: '我想你了', answer: '很想很想', source: '亲爱的热爱的' },
    { quote: '你到底想怎样', answer: '我想你离我远点', source: '流星花园' },
    { quote: '道歉有用的话', answer: '要警察干嘛', source: '流星花园' },
    { quote: '我是你的superstar', answer: '你永远是', source: '流星花园' },
    { quote: '女人', answer: '你引起了我的注意', source: '流星花园' },
    { quote: '此生不换', answer: '来生还要在一起', source: '仙剑奇侠传三' },
    { quote: '景天', answer: '你一定要好好的', source: '仙剑奇侠传三' },
    { quote: '六界之内', answer: '我只要你', source: '仙剑奇侠传三' },
    { quote: '雪见', answer: '我答应你', source: '仙剑奇侠传三' },
    { quote: '我不想你死', answer: '我也不想', source: '仙剑奇侠传三' },
    { quote: '世界那么大', answer: '我想去看看', source: '武林外传' },
    { quote: '排山倒海', answer: '葵花点穴手', source: '武林外传' },
    { quote: '子曾经曰过', answer: '那就不要曰了', source: '武林外传' },
    { quote: '照顾好我七舅姥爷', answer: '你的七舅姥爷是谁', source: '武林外传' },
    { quote: '好男人就是我', answer: '我就是曾小贤', source: '爱情公寓' },
    { quote: '一口盐汽水', answer: '喷死你', source: '爱情公寓' },
    { quote: '弹一闪', answer: '不要迷恋姐', source: '爱情公寓' },
    { quote: '你可能不太了解我', answer: '我其实是个很有趣的人', source: '爱情公寓' },
    { quote: '我的意大利炮呢', answer: '开炮', source: '亮剑' },
    { quote: '逢敌必亮剑', answer: '狭路相逢勇者胜', source: '亮剑' },
    { quote: '二营长', answer: '你他娘的意大利炮呢', source: '亮剑' },
    { quote: '不抛弃不放弃', answer: '这是我们班的规矩', source: '士兵突击' },
    { quote: '做有意义的事', answer: '就是好好活', source: '士兵突击' },
    { quote: '别以为我来坑你', answer: '我是来帮你的', source: '士兵突击' },
    { quote: '苏大强', answer: '我不吃我不喝我就要钱', source: '都挺好' },
    { quote: '蔡根花宝贝', answer: '大强你想我了吗', source: '都挺好' },
    { quote: '我的事不用你管', answer: '那怎么行你是我爸', source: '都挺好' },
    { quote: '看前面黑洞洞', answer: '定是那贼巢穴', source: '武林外传' },
    { quote: '确认过眼神', answer: '你是对的人', source: '庆余年' },
    { quote: '这个世界是你的', answer: '也是我的', source: '庆余年' },
    { quote: '我若成佛', answer: '天下无魔', source: '庆余年' },
    { quote: '我既不是好人', answer: '也不是坏人', source: '庆余年' },
    { quote: '你到底行不行', answer: '我不行你能行吗', source: '琅琊榜' },
    { quote: '既然你诚心诚意地发问了', answer: '那我就大发慈悲地告诉你', source: '琅琊榜' },
    { quote: '梅长苏', answer: '你到底是谁', source: '琅琊榜' },
    { quote: '活下去', answer: '活下去就是希望', source: '开端' },
  ],
  anime: [
    { quote: '真相只有一个', answer: '犯人就在我们中间', source: '名侦探柯南' },
    { quote: '我是个侦探', answer: '不是个杀手', source: '名侦探柯南' },
    { quote: '江户川柯南', answer: '是个侦探', source: '名侦探柯南' },
    { quote: '唯一看透真相', answer: '是一个外表看似小孩智慧却过于常人的名侦探柯南', source: '名侦探柯南' },
    { quote: '笨蛋', answer: '笨蛋笨蛋大笨蛋', source: '名侦探柯南' },
    { quote: '灰原', answer: '你是不是在吃醋', source: '名侦探柯南' },
    { quote: '我就是不认输', answer: '所以别想赢我', source: '名侦探柯南' },
    { quote: '我是要成为海贼王的男人', answer: '路飞你行的', source: '海贼王' },
    { quote: '人的梦想', answer: '是不会终结的', source: '海贼王' },
    { quote: '我是蒙奇·D·路飞', answer: '是要成为海贼王的人', source: '海贼王' },
    { quote: '我要成为海贼王', answer: '那就去大海上吧', source: '海贼王' },
    { quote: '因为我是你的伙伴', answer: '所以不管发生什么我都会在你身边', source: '海贼王' },
    { quote: '如果放弃的话', answer: '比赛就到此结束了', source: '灌篮高手' },
    { quote: '不到最后一刻', answer: '绝不放弃', source: '灌篮高手' },
    { quote: '教练我想打篮球', answer: '那你明天就来吧', source: '灌篮高手' },
    { quote: '因为我是天才', answer: '所以一定能进', source: '灌篮高手' },
    { quote: '你的运气很好', answer: '因为遇见了我', source: '灌篮高手' },
    { quote: '老爹你最辉煌的时刻是什么时候', answer: '而我就是现在了', source: '灌篮高手' },
    { quote: '我要用尽全力', answer: '守护到底', source: '排球少年' },
    { quote: '飞吧', answer: '向着更高的地方', source: '排球少年' },
    { quote: '正因为人没有翅膀', answer: '才会寻找飞翔的方法', source: '排球少年' },
    { quote: '我能在这里打排球', answer: '真是太好了', source: '排球少年' },
    { quote: '你为什么打排球', answer: '因为喜欢', source: '排球少年' },
    { quote: '我会一直前进', answer: '直到将巨人一个不剩地驱逐出去', source: '进击的巨人' },
    { quote: '把心脏献出去吧', answer: '心脏献出', source: '进击的巨人' },
    { quote: '这个世界是残酷的', answer: '但也是美丽的', source: '进击的巨人' },
    { quote: '那一天人类终于回想起了', answer: '被巨人支配的恐惧', source: '进击的巨人' },
    { quote: '我是自由的', answer: '所以我选择了战斗', source: '进击的巨人' },
    { quote: '我会成为火影', answer: '说到做到这就是我的忍道', source: '火影忍者' },
    { quote: '言出必行', answer: '这就是我的忍道', source: '火影忍者' },
    { quote: '我不会逃避', answer: '我不会退缩', source: '火影忍者' },
    { quote: '我要用我的方式', answer: '成为火影', source: '火影忍者' },
    { quote: '有话直说', answer: '这就是我的忍道', source: '火影忍者' },
    { quote: '我不会让我的同伴被杀', answer: '绝不', source: '火影忍者' },
    { quote: '我变秃了', answer: '也变强了', source: '一拳超人' },
    { quote: '你为什么这么强', answer: '因为我是埼玉', source: '一拳超人' },
    { quote: '我是一个兴趣使然的英雄', answer: '不是为了名利', source: '一拳超人' },
    { quote: '100次俯卧撑', answer: '100次仰卧起坐', source: '一拳超人' },
    { quote: '如果英雄只是兴趣', answer: '那就够了', source: '一拳超人' },
    { quote: '我是亚丝娜', answer: '请你记住我的名字', source: '刀剑神域' },
    { quote: '这虽然只是游戏', answer: '但可不是闹着玩的', source: '刀剑神域' },
    { quote: '我绝不会让任何人', answer: '再夺走我重要的人', source: '刀剑神域' },
    { quote: '星爆气流斩', answer: '二刀流', source: '刀剑神域' },
    { quote: '阿里嘎多', answer: '不用谢', source: '鬼灭之刃' },
    { quote: '我会成为最强的', answer: '斩鬼的一族', source: '鬼灭之刃' },
    { quote: '不要害怕', answer: '我会保护你', source: '鬼灭之刃' },
    { quote: '水之呼吸', answer: '壹之型 水面斩', source: '鬼灭之刃' },
    { quote: '炎之呼吸', answer: '壹之型 不知火', source: '鬼灭之刃' },
    { quote: '全集中', answer: '水之呼吸', source: '鬼灭之刃' },
    { quote: '火之神的神乐', answer: '圆舞', source: '鬼灭之刃' },
    { quote: '燃烧吧', answer: '把你的心也燃烧殆尽', source: '鬼灭之刃' },
    { quote: '只要你不放弃', answer: '奇迹就一定会发生', source: '灌篮高手' },
    { quote: '如果我是一个恶魔', answer: '那也是一个爱你的恶魔', source: '叛逆的鲁路修' },
    { quote: '你以为我是谁', answer: '我是西蒙', source: '天元突破' },
    { quote: '我的钻头', answer: '是突破天际的钻头', source: '天元突破' },
    { quote: '既然如此', answer: '那就创造一个没有神的世界', source: '反叛的鲁路修' },
    { quote: '错的不是我', answer: '是这个世界', source: '反叛的鲁路修' },
    { quote: '我毁灭了世界', answer: '又创造了世界', source: '反叛的鲁路修' },
    { quote: '我回来了', answer: '欢迎回来', source: '夏目友人帐' },
    { quote: '不可结缘', answer: '徒增寂寞', source: '夏目友人帐' },
    { quote: '看得见妖怪的孩子', answer: '总有一天会变得强大', source: '夏目友人帐' },
    { quote: '只要你还活着', answer: '就不会有真正的离别', source: '夏目友人帐' },
    { quote: '集齐七颗龙珠', answer: '就能召唤神龙', source: '龙珠' },
    { quote: '龟派气功', answer: '哈咩哈咩哈', source: '龙珠' },
    { quote: '我是孙悟空', answer: '来自地球的赛亚人', source: '龙珠' },
    { quote: '超越极限', answer: '这就是赛亚人的本能', source: '龙珠' },
    { quote: '我是一只兔子', answer: '我叫月野兔', source: '美少女战士' },
    { quote: '我要代表月亮消灭你', answer: '代我惩罚你', source: '美少女战士' },
    { quote: '选择死亡', answer: '还是选择战斗', source: '死亡笔记' },
    { quote: '我是新世界的神', answer: '这个世界的规则由我来定', source: '死亡笔记' },
    { quote: '只要写上名字', answer: '那个人就会死', source: '死亡笔记' },
    { quote: '人没有牺牲就什么都得不到', answer: '为了得到什么东西', source: '钢之炼金术师' },
    { quote: '等价交换', answer: '这就是炼金术的基本原则', source: '钢之炼金术师' },
    { quote: '一即是全', answer: '全即是一', source: '钢之炼金术师' },
    { quote: '站起来向前走', answer: '你不是还有腿吗', source: '钢之炼金术师' },
    { quote: '我已经没有什么好怕的了', answer: '因为我已经是最不幸的了', source: '魔法少女小圆' },
    { quote: '和我签订契约', answer: '成为魔法少女吧', source: '魔法少女小圆' },
    { quote: '奇迹不是免费的', answer: '如果你祈求希望', source: '魔法少女小圆' },
    { quote: '我亲手终结了一切', answer: '又重新开始了', source: '反叛的鲁路修' },
    { quote: '任意门', answer: '带我去任何地方', source: '哆啦A梦' },
    { quote: '大雄你真是个笨蛋', answer: '可是我也有优点啊', source: '哆啦A梦' },
    { quote: '只要我们有梦想', answer: '就没有做不到的事', source: '哆啦A梦' },
    { quote: '小姐小姐', answer: '你在看什么呢', source: '蜡笔小新' },
    { quote: '我要吃巧克力饼干', answer: '你已经吃很多了', source: '蜡笔小新' },
  ],
};

// ==================== 经典复刻 - 场景描述库 ====================
const sceneGuessData = {
  movie: [
    { scene: '一个和尚踩着七色云彩来救他的爱人，但摘下金箍后却无法拥抱她', answer: '大话西游', source: '电影' },
    { scene: '一个男人穿着燕尾服站在船头，张开双臂感受海风，身后女子抱住他的腰', answer: '泰坦尼克号', source: '电影' },
    { scene: '监狱的雨夜，男人从下水道爬出来，张开双臂迎接暴雨，重获自由', answer: '肖申克的救赎', source: '电影' },
    { scene: '一个傻子跑了半辈子，跑成了橄榄球明星、战争英雄、乒乓外交使者', answer: '阿甘正传', source: '电影' },
    { scene: '两个警察在警局天台对峙，一个说对不起我是警察另一个说谁知道', answer: '无间道', source: '电影' },
    { scene: '包租婆一大早扯着嗓子喊包租婆怎么没水了', answer: '功夫', source: '电影' },
    { scene: '一个男人在面摊吃面，偶遇心爱的女人说我养你啊', answer: '喜剧之王', source: '电影' },
    { scene: '两个小偷打扮成装修工人在别人家里吃火锅', answer: '疯狂的石头', source: '电影' },
    { scene: '一个人拿着一朵花在街头等心上人，被路人误会成变态', answer: '唐伯虎点秋香', source: '电影' },
    { scene: '一个少年在暴雨中张开双臂大声呼喊，身旁是一个巨大的钢铁巨人', answer: '钢铁侠', source: '电影' },
    { scene: '父女俩在洪水中失散，父亲用尽所有方法寻找女儿', answer: '亲爱的', source: '电影' },
    { scene: '一群人围坐在火锅旁，吃着吃着就吃出了人命', answer: '火锅英雄', source: '电影' },
    { scene: '一个人穿着打满补丁的西装，抱着女儿在厕所里哭', answer: '当幸福来敲门', source: '电影' },
    { scene: '一个绿怪物和一个驴子一起去救公主', answer: '怪物史莱克', source: '电影' },
    { scene: '一群超级英雄穿过传送门去外星打灭霸', answer: '复仇者联盟4', source: '电影' },
    { scene: '一个机器人收拾垃圾，遇到了另一个机器人，一起飞向太空', answer: '机器人总动员', source: '电影' },
    { scene: '一条鱼被潜水员抓走，父亲穿越整个海洋去寻找', answer: '海底总动员', source: '电影' },
    { scene: '一个老人用气球把房子飞起来，去实现和妻子的约定', answer: '飞屋环游记', source: '电影' },
    { scene: '一个骷髅在亡灵节穿越到人间寻找自己的家人', answer: '寻梦环游记', source: '电影' },
    { scene: '一只熊猫被选中成为神龙大侠', answer: '功夫熊猫', source: '电影' },
    { scene: '两个男人在火车上相遇，一个是警察一个是贼', answer: '天下无贼', source: '电影' },
    { scene: '一个男人穿越到20年前试图改变命运', answer: '夏洛特烦恼', source: '电影' },
    { scene: '一个女孩穿越到另一个世界，在汤屋打工', answer: '千与千寻', source: '电影' },
    { scene: '一对青梅竹马在山上系红绳许愿', answer: '你的名字', source: '电影' },
    { scene: '一个少年穿越时空去救一个女孩', answer: '铃芽之旅', source: '电影' },
    { scene: '一个和尚和一个妖怪谈恋爱，最后发现妖怪是好的', answer: '白蛇缘起', source: '电影' },
    { scene: '一个少年和一条狗一起坐着飞毯飞翔', answer: '阿拉丁', source: '电影' },
    { scene: '一群农民工在工地上发现了一块玉', answer: '疯狂的石头', source: '电影' },
    { scene: '一个男人穿着蝙蝠战衣站在哥谭市的高楼上', answer: '蝙蝠侠', source: '电影' },
    { scene: '一个被蜘蛛咬了的少年在城市间荡来荡去', answer: '蜘蛛侠', source: '电影' },
    { scene: '一个男孩用魔杖对抗黑魔王', answer: '哈利波特', source: '电影' },
    { scene: '一群人护送一枚戒指去火山销毁', answer: '指环王', source: '电影' },
    { scene: '一只小狮子在父亲死后流浪，最终回来夺回王位', answer: '狮子王', source: '电影' },
    { scene: '一个穿着燕尾服的男人坐在钢琴前弹奏，用弹钢琴的手法理发', answer: '功夫', source: '电影' },
    { scene: '一个男人为救女儿冲进医院与歹徒搏斗', answer: '让子弹飞', source: '电影' },
    { scene: '一个少年戴着金箍在沙漠中行走', answer: '大话西游', source: '电影' },
    { scene: '一个男人站在山顶对着远方大喊让子弹飞一会儿', answer: '让子弹飞', source: '电影' },
    { scene: '一个穿着战甲的士兵在冰天雪地中战斗', answer: '长津湖', source: '电影' },
    { scene: '一群中国海军在海外执行撤侨任务', answer: '红海行动', source: '电影' },
    { scene: '一个小偷假扮电影导演混进剧组', answer: '满江红', source: '电影' },
    { scene: '一个程序员发现自己生活在一个虚拟世界里', answer: '黑客帝国', source: '电影' },
    { scene: '一个宇航员在火星上种土豆求生', answer: '火星救援', source: '电影' },
    { scene: '一个父亲带着儿子在废土世界寻找幸存者', answer: '疯狂的麦克斯', source: '电影' },
    { scene: '一个老人得了老年痴呆，女儿照顾他的故事', answer: '困在时间里的父亲', source: '电影' },
    { scene: '一只猩猩学会了手语，与人类建立了友谊', answer: '猩球崛起', source: '电影' },
    { scene: '一个少年和一个老人一起坐飞屋旅行', answer: '飞屋环游记', source: '电影' },
    { scene: '一个赛车手穿越到汽车世界变成了赛车', answer: '赛车总动员', source: '电影' },
    { scene: '一只蓝鱼和一只黄鱼在海洋中冒险', answer: '海底总动员', source: '电影' },
    { scene: '一个少年在宇宙飞船上醒来发现自己独自一人', answer: '太空旅客', source: '电影' },
    { scene: '一个女孩在雨中获得了超能力', answer: '天气之子', source: '电影' },
    { scene: '一家人在亡灵节团聚，活着的人和死去的人在同一晚相会', answer: '寻梦环游记', source: '电影' },
    { scene: '一个少年用棋盘拯救世界，棋子就是真实的士兵', answer: '安德的游戏', source: '电影' },
    { scene: '一个父亲在集中营里用游戏的方式保护儿子的童心', answer: '美丽人生', source: '电影' },
    { scene: '一条忠犬在车站等待已经去世的主人，一等就是十年', answer: '忠犬八公的故事', source: '电影' },
    { scene: '一个摔跤手父亲训练女儿成为世界冠军', answer: '摔跤吧爸爸', source: '电影' },
    { scene: '一个男人在一个只有他一个人的城市里打怪', answer: '我是传奇', source: '电影' },
  ],
  skit: [
    { scene: '两个东北老农民上春晚，回忆过去一年的大事，从九八年说到改革春风', answer: '昨天今天明天', source: '小品' },
    { scene: '一个大爷去饭店请客吃饭，结果孙女在饭店当服务员', answer: '不差钱', source: '小品' },
    { scene: '一个卖拐的骗子把拐卖给了不需要拐的人', answer: '卖拐', source: '小品' },
    { scene: '一个老头和一个老太太在电视上相亲', answer: '相亲', source: '小品' },
    { scene: '一个钟点工在雇主家聊天，雇主穿着马甲', answer: '钟点工', source: '小品' },
    { scene: '一个饭店服务员吐槽菜单上的菜名都是骗人的', answer: '打工奇遇', source: '小品' },
    { scene: '两个人互相忽悠对方买自己的东西', answer: '同桌的你', source: '小品' },
    { scene: '一个农民捐款捐到了自己家', answer: '捐助', source: '小品' },
    { scene: '两个老人在公园里比赛谁更牛', answer: '牛大叔提干', source: '小品' },
    { scene: '一个保洁阿姨和一个总经理长得一模一样', answer: '真假总经理', source: '小品' },
    { scene: '两个人在饭桌上互相敬酒', answer: '酒逢知己', source: '小品' },
    { scene: '一个工人和老板谈加薪', answer: '谈工资', source: '小品' },
    { scene: '一个老奶奶摔倒了，路人在纠结扶不扶', answer: '扶不扶', source: '小品' },
    { scene: '一个小伙子拼命吃面条，一碗接一碗', answer: '吃面条', source: '小品' },
    { scene: '两个人争着演主角还是配角', answer: '主角与配角', source: '小品' },
    { scene: '一个小偷和警察在平安夜相遇', answer: '警察与小偷', source: '小品' },
    { scene: '一个人假装自己是经理来相亲', answer: '策划', source: '小品' },
    { scene: '一对夫妻因为一句话闹别扭', answer: '一句话的事儿', source: '小品' },
    { scene: '一个马屁精拼命讨好领导', answer: '投其所好', source: '小品' },
    { scene: '一群模特在排练时装秀', answer: '红高粱模特队', source: '小品' },
    { scene: '两个人在电视上互相对对联', answer: '拜年', source: '小品' },
    { scene: '一个装修工人大锤一锤八十小锤四十', answer: '装修', source: '小品' },
    { scene: '一个人买车被各种加价坑了', answer: '卖车', source: '小品' },
    { scene: '一个农民进城打工的奇遇', answer: '打工奇遇', source: '小品' },
    { scene: '两个东北老头老太太回忆往事', answer: '昨天今天明天', source: '小品' },
    { scene: '一个大爷在春晚舞台上唱二人转', answer: '红高粱模特队', source: '小品' },
    { scene: '一个人得了病到处求医问药', answer: '病了', source: '小品' },
    { scene: '一对夫妻在除夕夜吵架又和好', answer: '一句话的事儿', source: '小品' },
    { scene: '一个公交车司机每天遇到各种奇葩乘客', answer: '公交情缘', source: '小品' },
    { scene: '一个老太太在电视上选秀', answer: '火炬手', source: '小品' },
    { scene: '一个大爷假装有钱人去相亲', answer: '相亲', source: '小品' },
    { scene: '两个老朋友在公园下棋聊天', answer: '同桌的你', source: '小品' },
    { scene: '一家人过年回不了家在车站过年', answer: '回家过年', source: '小品' },
  ],
  tv: [
    { scene: '后宫嫔妃们为了争宠明争暗斗，最后甄嬛成为了太后', answer: '甄嬛传', source: '电视剧' },
    { scene: '一群格格在宫里闹翻天，小燕子总是闯祸', answer: '还珠格格', source: '电视剧' },
    { scene: '魏璎珞为了调查姐姐死因进宫，一路开挂升级', answer: '延禧攻略', source: '电视剧' },
    { scene: '三个结拜兄弟在乱世中各奔东西', answer: '三国演义', source: '电视剧' },
    { scene: '一群好汉上梁山聚义', answer: '水浒传', source: '电视剧' },
    { scene: '师徒四人去西天取经', answer: '西游记', source: '电视剧' },
    { scene: '一个男孩和一个女孩从小一起长大', answer: '情深深雨蒙蒙', source: '电视剧' },
    { scene: '一家人在四合院里生活的故事', answer: '家有儿女', source: '电视剧' },
    { scene: '几个年轻人在爱情公寓里合租', answer: '爱情公寓', source: '电视剧' },
    { scene: '一群年轻人在欢乐颂小区里生活', answer: '欢乐颂', source: '电视剧' },
    { scene: '一个男人穿越到古代当了皇帝', answer: '庆余年', source: '电视剧' },
    { scene: '一个少年在仙侠世界修炼成仙', answer: '仙剑奇侠传', source: '电视剧' },
    { scene: '一群人在长安城里破案', answer: '长安十二时辰', source: '电视剧' },
    { scene: '一个大学生和一个电竞选手谈恋爱', answer: '亲爱的热爱的', source: '电视剧' },
    { scene: '一个霸道总裁和一个普通女孩的故事', answer: '流星花园', source: '电视剧' },
    { scene: '一个普通家庭三十年的变迁', answer: '人世间', source: '电视剧' },
    { scene: '一个刑警队长追查连环杀人案', answer: '白夜追凶', source: '电视剧' },
    { scene: '一群盗墓贼下墓探险', answer: '盗墓笔记', source: '电视剧' },
    { scene: '一个客栈里聚集了一群江湖人物的日常', answer: '武林外传', source: '电视剧' },
    { scene: '一个男人和一条蛇精谈恋爱', answer: '三生三世十里桃花', source: '电视剧' },
    { scene: '一个将军带领独立团抗击日寇', answer: '亮剑', source: '电视剧' },
    { scene: '一个士兵从一个新兵成长为兵王', answer: '士兵突击', source: '电视剧' },
    { scene: '一个女官在朝堂上步步为营最终成为太后', answer: '琅琊榜', source: '电视剧' },
    { scene: '一个女孩在公交车上循环爆炸', answer: '开端', source: '电视剧' },
    { scene: '一家人因为父亲的养老问题闹得不可开交', answer: '都挺好', source: '电视剧' },
    { scene: '一个女孩在乱世中求生存最终成为皇后', answer: '知否知否应是绿肥红瘦', source: '电视剧' },
    { scene: '三个家庭的孩子高考的故事', answer: '小欢喜', source: '电视剧' },
    { scene: '三个小孩在海边发现了一具尸体', answer: '隐秘的角落', source: '电视剧' },
    { scene: '一个鱼贩从一个好人变成了黑恶势力头目', answer: '狂飙', source: '电视剧' },
    { scene: '一个出租车司机寻找一桩出租车杀人案真相', answer: '漫长的季节', source: '电视剧' },
    { scene: '一个女侦探在民国上海滩破案', answer: '民国奇探', source: '电视剧' },
    { scene: '一群大学生在民国时期参加革命', answer: '觉醒年代', source: '电视剧' },
    { scene: '一个少年在乱世中成长为一代宗师', answer: '一代枭雄', source: '电视剧' },
  ],
  anime: [
    { scene: '一个小学生变成了小孩子，追查黑衣组织', answer: '名侦探柯南', source: '动漫' },
    { scene: '一个草帽少年出海寻找宝藏', answer: '海贼王', source: '动漫' },
    { scene: '一个忍者少年追求成为火影', answer: '火影忍者', source: '动漫' },
    { scene: '一个少年收集七颗龙珠召唤神龙', answer: '龙珠', source: '动漫' },
    { scene: '一个少年用死亡笔记杀人', answer: '死亡笔记', source: '动漫' },
    { scene: '一个少年用进击的巨人之力保护人类', answer: '进击的巨人', source: '动漫' },
    { scene: '一个光头英雄一拳打败所有敌人', answer: '一拳超人', source: '动漫' },
    { scene: '一个少年用呼吸法斩鬼', answer: '鬼灭之刃', source: '动漫' },
    { scene: '一个少年进入刀剑神域游戏被困', answer: '刀剑神域', source: '动漫' },
    { scene: '一个少年能看到妖怪，和妖怪做朋友', answer: '夏目友人帐', source: '动漫' },
    { scene: '一个少年在篮球场上大杀四方', answer: '灌篮高手', source: '动漫' },
    { scene: '一群少年打排球', answer: '排球少年', source: '动漫' },
    { scene: '一个少年用炼金术拯救弟弟', answer: '钢之炼金术师', source: '动漫' },
    { scene: '一个少年和死神签订契约获得力量', answer: '死神', source: '动漫' },
    { scene: '一个少年在各种世界冒险', answer: 'RE:从零开始的异世界生活', source: '动漫' },
    { scene: '一个少年和精灵约会', answer: '约会大作战', source: '动漫' },
    { scene: '一个少年收集宝可梦', answer: '宝可梦', source: '动漫' },
    { scene: '一个少年用数码暴龙机召唤数码兽', answer: '数码宝贝', source: '动漫' },
    { scene: '一个少年穿越到异世界当勇者', answer: '关于我转生变成史莱姆这档事', source: '动漫' },
    { scene: '一个少女和猫男爵一起冒险', answer: '猫的报恩', source: '动漫' },
    { scene: '一个魔女骑着扫帚送快递', answer: '魔女宅急便', source: '动漫' },
    { scene: '两个姐妹在森林里遇到龙猫', answer: '龙猫', source: '动漫' },
    { scene: '一个少年用咒力战斗', answer: '咒术回战', source: '动漫' },
    { scene: '一个精灵和勇者一起旅行，勇者寿命将尽', answer: '葬送的芙莉莲', source: '动漫' },
    { scene: '一个间谍和一个杀手假结婚', answer: '间谍过家家', source: '动漫' },
    { scene: '一个武士在江户时代开了一家万事屋', answer: '银魂', source: '动漫' },
    { scene: '一个少年在猎人考试中冒险', answer: '全职猎人', source: '动漫' },
    { scene: '一个少女和魔法少女签订契约', answer: '魔法少女小圆', source: '动漫' },
    { scene: '一个小学生有个来自未来的猫型机器人', answer: '哆啦A梦', source: '动漫' },
    { scene: '一个五岁小男孩总是调戏大姐姐', answer: '蜡笔小新', source: '动漫' },
    { scene: '一个小学生和同学们的日常趣事', answer: '樱桃小丸子', source: '动漫' },
    { scene: '一个少年用意志力打败敌人', answer: 'JOJO的奇妙冒险', source: '动漫' },
  ],
};

// ==================== 看图猜影视 - 表情谜题库 ====================
const emojiGuessData = {
  movie: [
    { emoji: '🚢❄️💔', answer: '泰坦尼克号' },
    { emoji: '🌊🌍🧊', answer: '后天' },
    { emoji: '🍫🏃‍♂️🎁', answer: '阿甘正传' },
    { emoji: '🐵☁️💍', answer: '大话西游' },
    { emoji: '🦇👨‍🦲🃏', answer: '蝙蝠侠' },
    { emoji: '🕷️👦🏙️', answer: '蜘蛛侠' },
    { emoji: '🤖❤️👤', answer: '钢铁侠' },
    { emoji: '🦸‍♂️🦸‍♀️🦸‍♂️', answer: '复仇者联盟' },
    { emoji: '⚓⚔️🏴‍☠️', answer: '加勒比海盗' },
    { emoji: '🤝🔫👨‍🦱', answer: '无间道' },
    { emoji: '🦅⚔️👑', answer: '指环王' },
    { emoji: '💍🌋🧙‍♂️', answer: '指环王' },
    { emoji: '🦁👑🌅', answer: '狮子王' },
    { emoji: '🐜🦸‍♂️⚡', answer: '蚁人' },
    { emoji: '🐠🔍👨', answer: '海底总动员' },
    { emoji: '🤖🗑️🌱', answer: '机器人总动员' },
    { emoji: '🎈🏠👴', answer: '飞屋环游记' },
    { emoji: '💀🎸🎸', answer: '寻梦环游记' },
    { emoji: '🐼🥋🐉', answer: '功夫熊猫' },
    { emoji: '👻🚫👻', answer: '捉鬼敢死队' },
    { emoji: '🦖🦕🏝️', answer: '侏罗纪公园' },
    { emoji: '👽📞👨‍🚀', answer: 'E.T.外星人' },
    { emoji: '🌑🚀👨‍🚀', answer: '星际穿越' },
    { emoji: '🪐🕳️⏰', answer: '星际穿越' },
    { emoji: '🌪️💧🔥', answer: '后天' },
    { emoji: '👨‍🚀🌱🚀', answer: '火星救援' },
    { emoji: '🧊🚢⛰️', answer: '泰坦尼克号' },
    { emoji: '🍳👟🏃‍♂️', answer: '阿甘正传' },
    { emoji: '🎸🎤🤘', answer: '波西米亚狂想曲' },
    { emoji: '🐝🎬🍯', answer: '蜜蜂总动员' },
    { emoji: '🐭🍳👨‍🍳', answer: '料理鼠王' },
    { emoji: '🌍❄️🧊', answer: '冰河世纪' },
    { emoji: '🐯🔥👦', answer: '少年派的奇幻漂流' },
    { emoji: '🤖🚗💥', answer: '变形金刚' },
    { emoji: '🔪🕵️🌊', answer: '碟中谍' },
    { emoji: '🎭😂😭', answer: '人生大事' },
    { emoji: '🦸‍♂️🇺🇸🛡️', answer: '美国队长' },
    { emoji: '🔨⚡🦸‍♂️', answer: '雷神' },
    { emoji: '🟢😈🦹‍♂️', answer: '绿巨人' },
    { emoji: '🎭🤡 Gotham', answer: '小丑' },
    { emoji: '🐒☁️👑', answer: '大话西游' },
    { emoji: '🥋⚽💪', answer: '少林足球' },
    { emoji: '🎭💔🦋', answer: '霸王别姬' },
    { emoji: '🔫🐎💰', answer: '让子弹飞' },
    { emoji: '🔥🌎🌍', answer: '流浪地球' },
    { emoji: '👹🔥👶', answer: '哪吒之魔童降世' },
    { emoji: '🪖🇨🇳⚔️', answer: '战狼' },
    { emoji: '💊😷😢', answer: '我不是药神' },
    { emoji: '🏎️💨😄', answer: '飞驰人生' },
    { emoji: '⏰🔄💥', answer: '开端' },
    { emoji: '👨‍🏫📝❤️', answer: '死亡诗社' },
    { emoji: '🎪🤡😱', answer: '小丑回魂' },
    { emoji: '🐠🐠🐠', answer: '海底总动员' },
    { emoji: '🐉🔥👦', answer: '驯龙高手' },
  ],
  skit: [
    { emoji: '👴👴📺🎊', answer: '昨天今天明天' },
    { emoji: '👀💤👀☀️', answer: '不差钱' },
    { emoji: '🦵💸😵', answer: '卖拐' },
    { emoji: '👵💬👨', answer: '钟点工' },
    { emoji: '🍚🍲❌', answer: '不差钱' },
    { emoji: '🏨😂👨‍🍳', answer: '打工奇遇' },
    { emoji: '💰🎁😊', answer: '捐助' },
    { emoji: '👴👵💕', answer: '相亲' },
    { emoji: '🚌👨‍✈️😍', answer: '公交情缘' },
    { emoji: '🤵💰😢', answer: '谈工资' },
    { emoji: '🍺🥂👯', answer: '酒逢知己' },
    { emoji: '🌍🇨🇳👨', answer: '老外' },
    { emoji: '👵💥🙏', answer: '扶不扶' },
    { emoji: '🍜🥢😋', answer: '吃面条' },
    { emoji: '🎭👑🤡', answer: '主角与配角' },
    { emoji: '👮‍♂️🦹‍♂️🌙', answer: '警察与小偷' },
    { emoji: '🧹🔨💰', answer: '装修' },
    { emoji: '📺🎯👏', answer: '投其所好' },
    { emoji: '👨‍👩‍👧❤️📺', answer: '一句话的事儿' },
    { emoji: '🏃‍♂️🚗💨', answer: '卖车' },
    { emoji: '👵🔥🏃‍♂️', answer: '火炬手' },
    { emoji: '🏥😂🤧', answer: '病了' },
  ],
  tv: [
    { emoji: '👩‍🦰👑🗡️', answer: '甄嬛传' },
    { emoji: '👸🎀🐦', answer: '还珠格格' },
    { emoji: '👩‍🦰🐉⚔️', answer: '延禧攻略' },
    { emoji: '⚔️🐎👑', answer: '三国演义' },
    { emoji: '⛰️🙏108', answer: '水浒传' },
    { emoji: '🐵🧘‍♂️🐷', answer: '西游记' },
    { emoji: '❤️🌧️👩', answer: '情深深雨蒙蒙' },
    { emoji: '🏠👨‍👩‍👧‍👦', answer: '家有儿女' },
    { emoji: '🏠❤️😄', answer: '爱情公寓' },
    { emoji: '🎵👩‍🦰👩', answer: '欢乐颂' },
    { emoji: '⏰⚔️🏯', answer: '长安十二时辰' },
    { emoji: '🎮❤️👨', answer: '亲爱的热爱的' },
    { emoji: '💔💔💔', answer: '流星花园' },
    { emoji: '🍚👩‍🍳👨', answer: '都挺好' },
    { emoji: '⏰30🌙', answer: '三十而已' },
    { emoji: '👨‍🚀🌙🚀', answer: '你是我的荣耀' },
    { emoji: '⚔️🏮🏯', answer: '庆余年' },
    { emoji: '🐺🏔️🎯', answer: '琅琊榜' },
    { emoji: '🚌🔄💥', answer: '开端' },
    { emoji: '🗡️☀️👹', answer: '仙剑奇侠传' },
    { emoji: '🔥🚬⚖️', answer: '狂飙' },
    { emoji: '🍂🔍🚕', answer: '漫长的季节' },
    { emoji: '🪖🔫💥', answer: '亮剑' },
    { emoji: '🎖️💪🪖', answer: '士兵突击' },
    { emoji: '⚔️🐉❤️', answer: '三生三世十里桃花' },
    { emoji: '🎒📚😅', answer: '小欢喜' },
    { emoji: '🏔️👻👦', answer: '隐秘的角落' },
    { emoji: '📺🎥😢', answer: '人世间' },
  ],
  anime: [
    { emoji: '🔍👦🔪', answer: '名侦探柯南' },
    { emoji: '🏴‍☠️👒🌊', answer: '海贼王' },
    { emoji: '🦊🔥🍜', answer: '火影忍者' },
    { emoji: '🐉🌟7️⃣', answer: '龙珠' },
    { emoji: '📓✍️💀', answer: '死亡笔记' },
    { emoji: '🗿⚔️🧱', answer: '进击的巨人' },
    { emoji: '🥊👹🌊', answer: '鬼灭之刃' },
    { emoji: '🗡️🤺👻', answer: '死神' },
    { emoji: '🏐🏐🏐', answer: '排球少年' },
    { emoji: '🏀🔥👦', answer: '灌篮高手' },
    { emoji: '⚗️🤖🔩', answer: '钢之炼金术师' },
    { emoji: '👀👹📔', answer: '夏目友人帐' },
    { emoji: '⚡💎🎮', answer: '刀剑神域' },
    { emoji: '⚪🥊💥', answer: '一拳超人' },
    { emoji: '⚔️🧝‍♂️🌲', answer: '葬送的芙莉莲' },
    { emoji: '🕵️‍♂️🔮🎭', answer: '咒术回战' },
    { emoji: '🌸💔⚔️', answer: '鬼灭之刃' },
    { emoji: '🐱🤖⏰', answer: '哆啦A梦' },
    { emoji: '👦🖍️😏', answer: '蜡笔小新' },
    { emoji: '👧🍒😊', answer: '樱桃小丸子' },
    { emoji: '👾🎮🔄', answer: 'RE:从零开始的异世界生活' },
    { emoji: '💞👻🧙‍♀️', answer: '约会大作战' },
    { emoji: '🐭🧙‍♂️🔑', answer: '哈利波特' },
    { emoji: '👹🤡🎭', answer: 'JOJO的奇妙冒险' },
    { emoji: '👧🧹⚡', answer: '魔女宅急便' },
    { emoji: '🌲🐾😄', answer: '龙猫' },
    { emoji: '👨‍👩‍👧🔮✨', answer: '魔法少女小圆' },
    { emoji: '🕵️‍♂️🔪💒', answer: '间谍过家家' },
    { emoji: '⚔️😆🏪', answer: '银魂' },
    { emoji: '🎯🏹💪', answer: '全职猎人' },
    { emoji: '🔥🐉👦', answer: '驯龙高手' },
    { emoji: '⚡🐭🤖', answer: '宝可梦' },
  ],
};

// ==================== 工具函数 ====================
function getQuoteBattleWords(category) {
  const custom = (function() {
    try { return JSON.parse(localStorage.getItem('partygame_custom_qb') || '{}'); }
    catch (e) { return {}; }
  })();
  if (category === 'all') {
    let all = [];
    for (let cat in quoteBattleData) {
      all = all.concat(quoteBattleData[cat]);
      if (custom[cat]) all = all.concat(custom[cat]);
    }
    for (let cat in custom) {
      if (!quoteBattleData[cat]) all = all.concat(custom[cat]);
    }
    return all;
  }
  const builtin = quoteBattleData[category] || [];
  const userCustom = custom[category] || [];
  return builtin.concat(userCustom);
}

function getSceneGuessWords(category) {
  const custom = (function() {
    try { return JSON.parse(localStorage.getItem('partygame_custom_sg') || '{}'); }
    catch (e) { return {}; }
  })();
  if (category === 'all') {
    let all = [];
    for (let cat in sceneGuessData) {
      all = all.concat(sceneGuessData[cat]);
      if (custom[cat]) all = all.concat(custom[cat]);
    }
    for (let cat in custom) {
      if (!sceneGuessData[cat]) all = all.concat(custom[cat]);
    }
    return all;
  }
  const builtin = sceneGuessData[category] || [];
  const userCustom = custom[category] || [];
  return builtin.concat(userCustom);
}

function getEmojiGuessWords(category) {
  const custom = (function() {
    try { return JSON.parse(localStorage.getItem('partygame_custom_eg') || '{}'); }
    catch (e) { return {}; }
  })();
  if (category === 'all') {
    let all = [];
    for (let cat in emojiGuessData) {
      all = all.concat(emojiGuessData[cat]);
      if (custom[cat]) all = all.concat(custom[cat]);
    }
    for (let cat in custom) {
      if (!emojiGuessData[cat]) all = all.concat(custom[cat]);
    }
    return all;
  }
  const builtin = emojiGuessData[category] || [];
  const userCustom = custom[category] || [];
  return builtin.concat(userCustom);
}
